# Generated by Django 4.2.6 on 2024-05-06 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("spam_mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("set_is_active", "Активация рассылки")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="mailinglog",
            options={"verbose_name": "Лог", "verbose_name_plural": "Логи"},
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="client",
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="frequency",
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="send_time",
        ),
        migrations.RemoveField(
            model_name="mailinglog",
            name="server_response",
        ),
        migrations.RemoveField(
            model_name="mailinglog",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="message",
            name="mailing",
        ),
        migrations.AddField(
            model_name="mailing",
            name="clients",
            field=models.ManyToManyField(
                to="spam_mailing.client", verbose_name="Кому (клиенты сервиса)"
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="date_end",
            field=models.DateField(
                default=django.utils.timezone.now,
                verbose_name="Дата окончания рассылки",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="date_next",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="следующая дата рассылки",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="date_start",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата начала рассылки"
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активация рассылки"),
        ),
        migrations.AddField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="spam_mailing.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="name",
            field=models.CharField(
                default="Рассылка", max_length=100, verbose_name="Название рассылки"
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="period",
            field=models.CharField(
                choices=[
                    ("раз в день", "раз в день"),
                    ("раз в неделю", "раз в неделю"),
                    ("раз в месяц", "раз в месяц"),
                ],
                default="раз в день",
                max_length=30,
                verbose_name="Периодичность рассылки",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="start_time",
            field=models.TimeField(
                default=django.utils.timezone.now, verbose_name="Время рассылки"
            ),
        ),
        migrations.AddField(
            model_name="mailinglog",
            name="last_time_mail",
            field=models.DateTimeField(
                auto_now=True, verbose_name="дата и время последней попытки"
            ),
        ),
        migrations.AddField(
            model_name="mailinglog",
            name="response",
            field=models.TextField(blank=True, null=True, verbose_name="Ответ сервера"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("создана", "создана"),
                    ("завершена", "завершена"),
                    ("запущена", "запущена"),
                ],
                default="создана",
                max_length=30,
                verbose_name="Статус рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailinglog",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="spam_mailing.mailing",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AlterField(
            model_name="mailinglog",
            name="status",
            field=models.CharField(max_length=50, verbose_name="Статус попытки"),
        ),
    ]
