# Generated by Django 4.2.6 on 2024-04-28 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spam_mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Клиент", "verbose_name_plural": "Клиенты"},
        ),
    ]
