# Generated by Django 4.2.6 on 2024-04-29 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spam_mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="send_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 29, 19, 3, 36, 102637, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Время отправки",
            ),
        ),
    ]
