# Generated by Django 4.2.6 on 2024-05-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spam_mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("started", "Запущена"),
                    ("completed", "Завершена"),
                    ("stopped", "Остановлена"),
                ],
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
