# Generated by Django 4.2.6 on 2024-05-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spam_mailing", "0002_alter_mailing_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_view_mailing", "Can view mailing"),
                    ("can_stop_mailing", "Can stop mailing"),
                ]
            },
        ),
    ]
