# Generated by Django 4.2.6 on 2024-05-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spam_mailing", "0003_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={"permissions": [("disable_mailing", "Can disable mailing")]},
        ),
    ]
