# Generated by Django 4.2.6 on 2024-04-29 19:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("spam_mailing", "0003_alter_mailing_send_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="send_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Время отправки"
            ),
        ),
        migrations.AlterField(
            model_name="mailinglog",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="spam_mailing.mailing",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="mailing",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="spam_mailing.mailing",
                verbose_name="Рассылка",
            ),
        ),
    ]
