# Generated by Django 4.2.6 on 2024-04-28 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("spam_mailing", "0004_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время последней попытки"
                    ),
                ),
                (
                    "status",
                    models.CharField(max_length=10, verbose_name="Статус попытки"),
                ),
                (
                    "server_response",
                    models.TextField(verbose_name="Ответ почтового сервера"),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spam_mailing.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
        ),
    ]
