# Generated by Django 4.2.6 on 2024-04-30 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "spam_mailing",
            "0004_alter_mailing_send_time_alter_mailinglog_mailing_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="mailing",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message",
                to="spam_mailing.mailing",
                verbose_name="Рассылка",
            ),
        ),
    ]
