# Generated by Django 4.2.6 on 2024-05-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="static/images/",
                verbose_name="Изображение",
            ),
        ),
    ]
