# Generated by Django 4.2.6 on 2024-04-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
