# Generated by Django 4.2.6 on 2024-04-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_is_verified_user_verification_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="have_permissions",
            field=models.BooleanField(default=False, verbose_name="Права доступа"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Верификация"),
        ),
        migrations.AlterField(
            model_name="user",
            name="verification_code",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Код верификации"
            ),
        ),
    ]
